services:
  Macopedia\Bundle\TpayBundle\Method\View\TpayBlikView:
    arguments:
      - '@macopedia_tpay.legal'
      - '@form.factory'
    tags:
      - { name: oro_tpay.payment.method.view }

  Macopedia\Bundle\TpayBundle\Method\TpayBlikMethod:
    arguments:
      - '@macopedia_tpay.payment.payload.factory'
      - '@macopedia_tpay.gateway.factory'
      - '@macopedia_tpay.payment.response.factory'
      - '@logger'
      - '@macopedia_tpay.factory.notification_verifier'
      - '@router'
      - '@macopedia_tpay.tpay.channel_provider'
    tags:
      - { name: oro_tpay.payment.method }
