services:
  Macopedia\Bundle\TpayBundle\Method\View\TpayCardView:
    arguments:
      - '@macopedia_tpay.legal'
      - '@form.factory'
      - '@macopedia_tpay.payment.card.saved_card_handler'
    tags:
      - { name: oro_tpay.payment.method.view }

  Macopedia\Bundle\TpayBundle\Method\TpayCardMethod:
    arguments:
      - '@macopedia_tpay.payment.payload.createtransaction'
      - '@macopedia_tpay.payment.payload.factory'
      - '@macopedia_tpay.gateway.factory'
      - '@macopedia_tpay.payment.response.factory'
      - '@logger'
      - '@request_stack'
      - '@macopedia_tpay.factory.notification_verifier'
      - '@macopedia_tpay.payment.card.saved_card_handler'
      - '@macopedia_tpay.tpay.channel_provider'
    tags:
      - { name: oro_tpay.payment.method }
