services:
  Macopedia\Bundle\TpayBundle\Method\View\TpayPragmaPayView:
    public: false
    arguments:
      - '@macopedia_tpay.legal'
    tags:
      - { name: oro_tpay.payment.method.view }

  Macopedia\Bundle\TpayBundle\Method\TpayPragmaPayMethod:
    public: false
    arguments:
      - '@macopedia_tpay.payment.payload.factory'
      - '@macopedia_tpay.gateway.factory'
      - '@macopedia_tpay.payment.response.factory'
      - '@logger'
      - '@macopedia_tpay.factory.notification_verifier'
      - '@macopedia_tpay.tpay.channel_provider'
    tags:
      - { name: oro_tpay.payment.method }
